#!/usr/bin/env bash

# Check if UFW is installed
if ! command -v ufw &> /dev/null
then
    echo "UFW is not installed. Installing now..."
    apt-get update
    apt-get install ufw
fi

# Configure UFW
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp --force
ufw allow 443/tcp --force
ufw allow 80/tcp --force
ufw enable
